#!/usr/bin/env bun
// Regenerate src/ui/splash-art.ts from .ignore/splash/frame/nine/2-*.png.
// Rerun only when source art changes. The 8 baked string[] pieces +
// FRAME geometry are all the runtime needs — no chafa exec on launch.
//
// Locked config (.ignore/splash/frame/PICK.md):
//   2src, tile, tw=20 tv=8, braille, none-fg, corner 16×8

import { spawnSync } from "child_process"
import { writeFileSync } from "fs"

const DIR = `${import.meta.dir}/../.ignore/splash/frame/nine`
const OUT = `${import.meta.dir}/../src/ui/splash-art.ts`

const CW = 16, CH = 8   // corner
const TW = 20, TV = 8   // edge tile period (H, V)

const chafa = (name: string, w: number, h: number): string[] => {
  const r = spawnSync("chafa", [
    `--size=${w}x${h}`, "--format=symbols", "--symbols=braille",
    "--colors=none", "--fg-only", "--stretch", `${DIR}/2-${name}.png`,
  ], { encoding: "utf8" })
  if (r.status !== 0) { console.error(`chafa 2-${name}.png:`, r.stderr); process.exit(1) }
  // chafa can undershoot a row/col at odd targets — pad then clip exact.
  const lines = r.stdout.split("\n").filter(l => l.length)
  while (lines.length < h) lines.push("")
  return lines.slice(0, h).map(l => [...l].slice(0, w).join("").padEnd(w))
}

const PIECES = {
  TL: chafa("tl", CW, CH), TR: chafa("tr", CW, CH),
  BL: chafa("bl", CW, CH), BR: chafa("br", CW, CH),
  T: chafa("t", TW, CH), B: chafa("b", TW, CH),
  L: chafa("l", CW, TV), R: chafa("r", CW, TV),
}

const lit = (name: string, v: string[]) =>
  `const ${name} = [\n${v.map(l => `  ${JSON.stringify(l)},`).join("\n")}\n]`

writeFileSync(OUT, `\
// GENERATED by scripts/bake-splash.ts — do not edit.
// Baked braille 9-patch frame pieces for the launch splash (herm-tji.2).
// Source: .ignore/splash/frame/nine/2-*.png @ PICK.md settings.

/* eslint-disable */

export const FRAME = { cw: ${CW}, ch: ${CH}, tw: ${TW}, tv: ${TV} } as const

${Object.entries(PIECES).map(([k, v]) => lit(k, v)).join("\n\n")}

export type Inner = { x: number; y: number; w: number; h: number }

/** Assemble the frame at terminal size. Returns the full row list plus
 *  the inner text window (where wordmark + info + prompt go). Rows are
 *  exactly \`w\` grapheme-columns wide. Returns no frame below minimum. */
export function frame(w: number, h: number): { lines: string[]; inner: Inner } {
  const { cw, ch, tw, tv } = FRAME
  const mw = w - 2 * cw
  const mh = h - 2 * ch
  const inner: Inner = { x: cw, y: ch, w: Math.max(0, mw), h: Math.max(0, mh) }
  if (mw < 4 || mh < 2) return { lines: [], inner }

  const repH = (p: string[], span: number) =>
    p.map(l => l.repeat(Math.ceil(span / tw)).slice(0, span))
  const repV = (p: string[], span: number) =>
    Array.from({ length: span }, (_, i) => p[i % tv])

  const t = repH(T, mw), b = repH(B, mw)
  const l = repV(L, mh), r = repV(R, mh)
  const mid = " ".repeat(mw)

  const out: string[] = []
  for (let i = 0; i < ch; i++) out.push(TL[i] + t[i] + TR[i])
  for (let i = 0; i < mh; i++) out.push(l[i] + mid + r[i])
  for (let i = 0; i < ch; i++) out.push(BL[i] + b[i] + BR[i])
  return { lines: out, inner }
}
`)

console.log(`wrote ${OUT}`)
for (const [k, v] of Object.entries(PIECES)) {
  console.log(`  ${k}: ${v[0].length}×${v.length}`)
}
