#!/usr/bin/env bun
/**
 * Regenerate src/theme/manifest.ts from the JSON files in src/theme/themes/.
 * Run when a theme is added, removed, or its primary/accent/background changes.
 */

import { readdir } from "node:fs/promises"
import { join } from "node:path"

type Ref = string | { dark?: Ref; light?: Ref } | undefined
type Defs = Record<string, Ref>

const ROOT = join(import.meta.dir, "..", "src", "theme", "themes")
const OUT = join(import.meta.dir, "..", "src", "theme", "manifest.ts")

function resolve(c: Ref, defs: Defs, theme: Defs): string | null {
  if (c === undefined) return null
  if (typeof c === "object") return resolve(c.dark, defs, theme)
  if (c.startsWith("#")) return c
  if (c === "transparent" || c === "none") return "transparent"
  const nxt = defs[c] ?? theme[c]
  if (nxt === undefined) return null
  return resolve(nxt, defs, theme)
}

const files = (await readdir(ROOT)).filter(f => f.endsWith(".json")).sort()
const entries: string[] = []
for (const file of files) {
  const name = file.replace(/\.json$/, "")
  const json = await Bun.file(join(ROOT, file)).json()
  const defs = json.defs ?? {}
  const theme = json.theme ?? {}
  const primary = resolve(theme.primary, defs, theme)
  const accent = resolve(theme.accent, defs, theme)
  const background = resolve(theme.background, defs, theme)
  entries.push(`  ${JSON.stringify(name)}: { primary: ${JSON.stringify(primary)}, accent: ${JSON.stringify(accent)}, background: ${JSON.stringify(background)} },`)
}

const body = `/**
 * Theme manifest — generated by scripts/gen-theme-manifest.ts.
 * One tiny entry per built-in theme: name + a few preview colors for the picker.
 * Picker renders from this without loading any theme body (see ./load.ts).
 */

export type ThemePreview = {
  primary: string | null
  accent: string | null
  background: string | null
}

export const PREVIEW: Record<string, ThemePreview> = {
${entries.join("\n")}
}

export const NAMES: readonly string[] = Object.keys(PREVIEW).sort()
`

await Bun.write(OUT, body)
console.log(`wrote ${OUT} (${files.length} themes)`)
